PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX doap: <http://usefulinc.com/ns/doap#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <https://www.w3.org/2000/01/rdf-schema#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX org: <https://www.w3.org/ns/org#>
PREFIX time: <https://www.w3.org/2006/time#>
PREFIX owl: <https://www.w3.org/2002/07/owl#>

CONSTRUCT {
?URI rdf:type doap:Project;
	dbp:number ?code_du_projet;
	doap:name ?titre;
	xsd:string ?acronyme;
	xsd:string ?code_d_appel_a_projet;
	xsd:string ?appel_a_projet;
	time:hasBeginning ?date_de_debut;
	time:hasEnd ?date_de_fin;
	doap:description ?resume;
	dbp:number ?duree;
	dbp:number ?montant;
	foaf:topic ?theme;
	xsd:string ?code_rcn;
	doap:homepage ?lien_cordis;
	dcat:keyword ?mots_cles;
	org:linkedTo ?URI2.
?URI2 rdf:type dbo:Organisation;
	xsd:string ?identifiant_de_partenaire;
	xsd:string ?type_d_identifiant;
	rdfs:label ?libelle_de_partenaire;
	dbo:type ?URI3;
	dbo:nationality ?URI4.
?URI3 rdf:type owl:Class;
	rdfs:label  ?code_du_type_de_partenaire.
?URI4 rdf:type dbo:nationality;
	rdfs:label ?code_pays.
}
FROM <file:csv.csv>
WHERE {
  BIND (URI(CONCAT('http://ex.org/Projet/', ?titre)) AS ?URI)
  BIND (URI(CONCAT('http://ex.org/Participants/', ?sigle_de_partenaire)) AS ?URI2)
  BIND (URI(CONCAT('http://ex.org/Participants/Type/', ?type_de_partenaire)) AS ?URI3)
  BIND (URI(CONCAT('http://ex.org/Participants/Nationalite/', ?pays_du_partenaire)) AS ?URI4)
  BIND (xsd:integer(?Id) AS ?code_du_projet)
  BIND (xsd:integer(?dureeInt) AS ?duree)
  BIND (xsd:float(?montantF) AS ?montant)
}
